# Generated by Django 6.0.1 on 2026-01-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
